version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev

  backend:
    build:
      context: ./backend
      args:
        - CGO_ENABLED=1
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - openfga

  openfga:
    image: openfga/openfga:latest
    ports:
      - "8081:8081" # api
      - "3001:3001" # grpc
      - "8082:8082" # http
    command: run